### ISSUE TITLE
请问训练数据如何处理？

### ISSUE THREAD

**Issue by JessyMu** [stylellm/stylellm_models#1]

**Comment by stylellm** [comment]
> _No description provided._

主要就是构造平行语料的思路，小说文本先分段，再分别用回译或者大模型改写的方法给配上相应的去风格文本

**Comment by laiping-lp** [comment]
请问训练成本高吗

**Comment by stylellm** [comment]
> 请问训练成本高吗

可以用Lora训练，需要有一块16GB以上显存的GPU

**Comment by Leekinxun** [comment]
请问是直接二次预训练吗，还是进行相关的指令微调

**Comment by 666-bit** [comment]
同问，顺便请问模型进行了预训练，指令微调，DPO吗？

> 请问是直接二次预训练吗，还是进行相关的指令微调

**Comment by shenhaitao010** [comment]
同问，顺便请问模型进行了预训练，指令微调，DPO吗？

**Comment by stylellm** [comment]
统一回复一下上面几个问题。
发布的几个模型是在yi-6b的基础上做sft+rlhf，没有二次预训练。
